#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# TestController
index:
    path: /
    controller: App\Controller\TestController::Hello
# NumberController
lucky_number:
    path: /number/
    controller: App\Controller\NumberController::Number
