#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# TestController
index:
    path: /
    controller: App\Controller\MainController::Index


indextest:
    path: /test
    controller: App\Controller\MainController::Test
